fixtures:
  forge_modules:
    ntp:
      repo: "puppetlabs/ntp"
      ref: "4.1.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.9.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "1.4.2"
    r10k:
      repo: "zack/r10k"
      ref: "3.1.1"
    motd:
      repo: "saz/motd"
      ref: "2.3.1"
  repositories:
    hiera:
      repo: "https://github.com/GeoffWilliams/puppet-hiera"
      branch: "double_gem"
    mcollective_user: "https://github.com/GeoffWilliams/geoffwilliams-mcollective_user"
    puppet_enterprise: "https://github.com/GeoffWilliams/geoffwilliams-puppet_enterprise"
  symlinks:
    roles: "#{source_dir}/site/roles"
    profiles: "#{source_dir}/site/profiles"

