HOSTS:
  pe-puppet.localdomain:
    roles:
      - "agent"
      - "master"
    platform: "el-7-x86_64"
    image: "pe2015-2-0_aio-master"
    ssh_installed: true
    hypervisor : "docker"
CONFIG:
  log_level: "debug"
  masterless: true

