HOSTS:
  centos7:
#    roles:
#      - "agent"
    platform: "el-7-x86_64"
    image: "centos:7"
    hypervisor : "docker"
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - "yum -y install git"
#      - "yum -y install https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm"
#      - "yum -y install puppet"
#      - "ln -s /opt/puppetlabs/puppet/bin/puppet /usr/bin/puppet"
CONFIG:
#  type: "aio"
  log_level: "debug"
  masterless: true

