HOSTS:
  pe-puppet.localdomain:
    roles:
      - "agent"
      - "master"
    platform: "el-7-x86_64"
    docker_cmd: '["/sbin/init"]'

#    image: "pe2015-2-0_aio-master"
    image: "geoffwilliams/pe2015-2-1_centos-7_aio-master_public:v1"
#    dockerfile: "./spec/Dockerfile"
    hypervisor : "docker"
CONFIG:
  log_level: "debug"
  masterless: true

