HOSTS:
  pe-puppet.localdomain:
    roles:
      - "agent"
      - "master"
    platform: "el-7-x86_64"
    docker_cmd: '["/sbin/init"]'
    image: "geoffwilliams/pe2015.2.2_centos-7_aio-master_public_lowmem:v0"
    hypervisor : "docker"
    docker_preserve_image: true
CONFIG:
  log_level: "trace"
  masterless: true

